# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.0
language: swift
xcode_project: Example/MediaView.xcworkspace #3
xcode_scheme: MediaView-Example #4
xcode_sdk: iphonesimulator11.0

notifications:
  email: false

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/MediaView.xcworkspace -scheme MediaView-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
